### ISSUE TITLE
milestone (11/13-11/18)

### ISSUE THREAD

**Issue by fj68** [taulukointipalvelut/utab-view#3]
# 11/13

- [x] routing決定
- [x] コンポーネントファイル作成
- [ ] メニュー作成

# 11/14

レスポンシブよりもスマホでの表示を優先し、PCへの最適化は後でやる

- [x] スコシ入力のhome
- [ ] ジャッジごとのスコアシート
- [ ] スコシ確認
- [ ] エバシ入力のhome
- [ ] エバシ確認
- [ ] ジャッジごとのエバリュエーションシート

# 11/15

- [ ] データ入力のhome
- [x] tournament一覧と追加・削除
- [ ] venue一覧と追加・削除
- [ ] institution一覧と追加・削除
- [ ] speaker一覧と追加・削除
- [ ] team一覧と追加・削除
- [ ] adjudicator一覧と追加・削除
- [x] Roundのhome
- [ ] check-in venue
- [ ] check-in team
- [ ] check-in adjudicator

# 11/16

- [ ] draw creation
- [x] draw表示
- [x] allocation済みdrawの表示
- [ ] drawの候補表示
- [ ] allocationの候補表示
- [ ] team standings
- [ ] speaker standings
- [ ] adjudicator standings

# 11/17

- [ ] venue変更操作
- [ ] draw変更操作
- [ ] allocation変更操作

# 11/18

- [ ] import from csv

left for debugging

**Comment by fj68** [comment]
documentation & example

**Comment by nswa17** [comment]
組み直してほしい.
